import glob
import os

import numpy as np
import pandas as pd
import tensorflow as tf
from tensorflow.keras import layers, models


BASE_DIR = os.path.dirname(os.path.abspath(__file__))
DATASET_DIR = os.path.join(BASE_DIR, "TraningData")
MODEL_DIR = os.path.join(BASE_DIR, "Models")
SEQ_LENGTH = 128
NUM_SENSORS = 3
EPOCHS = 50
BATCH_SIZE = 64
VALIDATION_SPLIT = 0.2
CLASS_NAMES = ["0", "1", "2", "3", "4", "5", "6", "7"]


def load_data():
    x = []
    y = []

    print("开始加载数据...")
    for label_idx, class_name in enumerate(CLASS_NAMES):
        folder_path = os.path.join(DATASET_DIR, class_name)
        csv_files = glob.glob(os.path.join(folder_path, "*.csv"))
        print(f"正在处理类别 '{class_name}' (Label: {label_idx}), 共找到 {len(csv_files)} 个文件")

        for file_path in csv_files:
            try:
                df = pd.read_csv(file_path, header=None)
                data = df.values

                if data.shape[0] < SEQ_LENGTH:
                    padding = np.zeros((SEQ_LENGTH - data.shape[0], NUM_SENSORS))
                    data = np.vstack((data, padding))
                elif data.shape[0] > SEQ_LENGTH:
                    data = data[:SEQ_LENGTH, :]

                if data.shape[1] > NUM_SENSORS:
                    data = data[:, :NUM_SENSORS]

                x.append(data)
                y.append(label_idx)
            except Exception as e:
                print(f"读取文件错误: {file_path}, {e}")

    x = np.array(x, dtype=np.float32)
    y = np.array(y, dtype=np.int32)

    print("\n加载完成!")
    print(f"输入数据形状 X: {x.shape}")
    print(f"标签数据形状 y: {y.shape}")
    return x, y


def create_model(num_classes):
    model = models.Sequential(
        [
            layers.Input(shape=(SEQ_LENGTH, NUM_SENSORS)),
            layers.Conv1D(16, 3, activation="relu", padding="same"),
            layers.MaxPooling1D(2),
            layers.Conv1D(8, 3, activation="relu", padding="same"),
            layers.MaxPooling1D(2),
            layers.Flatten(),
            layers.Dense(16, activation="relu"),
            layers.Dropout(0.3),
            layers.Dense(num_classes, activation="softmax"),
        ]
    )
    model.compile(optimizer="adam", loss="sparse_categorical_crossentropy", metrics=["accuracy"])
    return model


def representative_dataset_gen(x_train):
    for i in range(len(x_train)):
        yield [x_train[i].reshape(1, SEQ_LENGTH, NUM_SENSORS)]


def convert_to_c_array(tflite_model, output_path, array_name="gesture_model_quant_tflite"):
    hex_data = ", ".join([f"0x{byte:02x}" for byte in tflite_model])
    content = f"""#include "gesture_model.h"
// Auto-generated by train_model.py
// Model Size: {len(tflite_model)} bytes
const unsigned char {array_name}[] = {{
  {hex_data}
}};

const int {array_name}_len = {len(tflite_model)};
"""
    with open(output_path, "w", encoding="utf-8") as f:
        f.write(content)
    print(f"C source file saved to {output_path}")


def main():
    os.makedirs(MODEL_DIR, exist_ok=True)

    x, y = load_data()
    if x is None or len(x) == 0:
        print("No data loaded. Exiting.")
        return

    model = create_model(len(CLASS_NAMES))
    model.summary()
    model.fit(x, y, epochs=EPOCHS, batch_size=BATCH_SIZE, validation_split=VALIDATION_SPLIT)

    converter = tf.lite.TFLiteConverter.from_keras_model(model)
    converter.optimizations = [tf.lite.Optimize.DEFAULT]
    converter.representative_dataset = lambda: representative_dataset_gen(x[:100])
    converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
    converter.inference_input_type = tf.int8
    converter.inference_output_type = tf.int8

    tflite_model = converter.convert()

    tflite_path = os.path.join(MODEL_DIR, "gesture_model_quant.tflite")
    with open(tflite_path, "wb") as f:
        f.write(tflite_model)
    print(f"TFLite model saved to {tflite_path}")

    convert_to_c_array(tflite_model, os.path.join(MODEL_DIR, "gesture_model.cc"))


if __name__ == "__main__":
    main()
